export const BADGES_DATA = [
  { id: 1, title: 'Все' },
  { id: 2, title: 'ИКТ' },
  { id: 3, title: 'гетика' },
  { id: 4, title: 'Механика' },
  { id: 5, title: 'Физика' },
  { id: 6, title: 'Сохтмон' },
  { id: 7, title: 'Агро' },
  { id: 8, title: 'Экология' },
  { id: 9, title: 'Гео' },
  { id: 10, title: 'Истехсолот' },
  { id: 11, title: 'Авиа' },
  { id: 12, title: 'Механика' },
  { id: 13, title: 'Математика' },
  { id: 14, title: 'Кимиё' },
];
