import {
  GenderIgnore,
  ChoiceCourses,
  CareerDecide,
  Tips,
  Work,
  Newspaper,
  ChildCareer,
  Achivments,
  Interview,
} from '@/shared';
import { TCardMoreProps } from '@/entities';

export const moreDataCareer: TCardMoreProps[] = [
  {
    imageSrc: CareerDecide,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Краткое руководство по принятию карьерных решений',
    date: '1 сентября',
    buttonText: 'Подробнее',
    link: '/fraud-prevention',
  },
  {
    imageSrc: GenderIgnore,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Как игнорировать гендерную предвзятость в профессиях',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Выбор предпочтений курса',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Tips,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title:
      '10 советов, которые помогут вам построить успешную творческую карьеру',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Work,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title:
      '10 способов уменьшить количество слов в заявлениях о приеме на работу',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Newspaper,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: '11  мест для поиска работы',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChildCareer,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: '11 советов, чтобы повысить интерес вашего ребенка к карьере',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Achivments,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: '15 вопросов, которые помогут написать сильные достижения',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Interview,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: '3 шага для преодолеия рынка труда выпускников',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
];
