import {
  ChoiceCourses,
  NutritionServices,
  AdminServices,
  AgriculturulCard,
  ServicesArea,
  Construction,
  Education,
  PowerSupply,
  FinancialServices,
  MedicalCare,
  Media,
  Production,
  Extraction,
  OthersServices,
  Science,
  Safety,
} from '@/shared';
import { TCardProps } from '@/entities';

export const moreDataIndustries: TCardProps[] = [
  {
    imageSrc: NutritionServices,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Услуги по размещению и питанию',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: AdminServices,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Административные и вспомогательные услуги',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: AgriculturulCard,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Сельское хозяйство, лесоводство и рыболовство',
    buttonText: 'Подробнее',
    link: '/agricultural-industry',
  },
  {
    imageSrc: ServicesArea,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Услуги в области искусства и отдыха',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Construction,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Строительство',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Education,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Образование и профессиональная подготовка',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: PowerSupply,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title:
      'Услуги по электроснабжению, газоснабжению, водоснабжению и утилизации отходов',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: FinancialServices,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Финансовые и страховые услуги',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: MedicalCare,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Медицинское обслуживание и социальная помощь',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Media,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Средства массовой информации и телекоммуникации',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Production,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Производство',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Extraction,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Добыча полезных ископаемых',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: OthersServices,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Другие услуги',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Science,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Профессиональные, научные и технические услуги',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Safety,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Государственное управление и безопасность',
    buttonText: 'Подробнее',
  },
];
