version: '3.8'

services:
  front:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  nginx_prod:
    container_name: 'nginx_prod'
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/nginx
      - /etc/letsencrypt/live/kasbiman.pro/fullchain.pem:/nginx/certificate.crt:ro
      - /etc/letsencrypt/live/kasbiman.pro/privkey.pem:/nginx/private.key:ro
    depends_on:
      - back