import {
  Follow,
  Development,
  Preparation,
  Mentoring,
  Achievement,
  Internship,
  CompilationTechniques,
  TimeManagement,
  BasicsEntrepreneurship,
  PracticalSkills,
  CareerProspects,
  InfoDiff,
} from '@/shared';
import { TCardProps } from '@/entities';

export const MORE_DATA_PARENTS: TCardProps[] = [
  {
    imageSrc: Follow,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Исследование профессиональных профилей и карьерных путей',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Development,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Развитие ключевых компетенций и навыков для успешной карьеры',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Preparation,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Информация о различных профессиональных областях и специализациях',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: InfoDiff,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Менторство и консультирование в процессе карьерного развития',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Mentoring,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Менторство и консультирование в процессе карьерного развития',
    buttonText: 'Подробнее',
  },

  {
    imageSrc: Achievement,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Роль образования в достижении карьерных целей',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Internship,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Возможности стажировок и практик для получения опыта работы',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: CompilationTechniques,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Техники составления профессионального портфолио и резюме',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: TimeManagement,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title:
      'Управление временем и планирование для достижения карьерных успехов',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: BasicsEntrepreneurship,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Основы предпринимательства и создания собственного бизнеса',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: PracticalSkills,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Практические навыки для успешного собеседования и трудоустройства',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: CareerProspects,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Карьерные перспективы в мире цифровых технологий и инноваций',
    buttonText: 'Подробнее',
  },
];
