export const districts = [
  { value: 'Dushanbe', label: 'Душанбе' },
  { value: 'Bokhtar', label: 'Бохтар (Курғон-Теппа)' },
  { value: 'Kulob', label: 'Кӯлоб' },
  { value: 'Vahdat', label: 'Ваҳдат' },
  { value: 'Tursunzoda', label: 'Турсунзода' },
  { value: 'Panjakent', label: 'Панҷакент' },
  { value: 'Norak', label: 'Норак' },
  { value: 'Danghara', label: 'Данғара' },
  { value: 'Farkhor', label: 'Фархор' },
  { value: 'Hissor', label: 'Ҳисор' },
  { value: 'Gafurov', label: 'Бобоҷон Ғафуров' }, // Assumed match
  { value: 'Roghun', label: 'Роғун' },
  { value: 'Shahritus', label: 'Шаҳритӯз' },
  { value: 'Shahrinav', label: 'Шаҳринав' },
  { value: 'Taboshar', label: 'Қайроқум (Табошар)' },
  { value: 'Chkalovsk', label: 'Бустон (Чкаловск)' },
  { value: 'Khorugh', label: 'Хоруғ' },
  { value: 'Murghab', label: 'Мурғоб' },
  { value: 'Qayroqqum', label: 'Гулистон (Қайроққум)' },
  { value: 'Sarband', label: 'Левакант (Сарбанд)' },
  { value: 'Vose', label: 'Восеъ' },
  { value: 'Asht', label: 'Ашт' },
  { value: 'Baljuvon', label: 'Балҷувон' },
  { value: 'Darvoz', label: 'Дарвоз' },
  { value: 'Devashtich', label: 'Ғончӣ (Деваштич)' },
  { value: 'Fayzobod', label: 'Файзобод' },
  { value: 'Ishkoshim', label: 'Ишкошим' },
  { value: 'Jabbor Rasulov', label: 'Расулов' }, // Assumed match
  { value: 'Jilikul', label: 'Дӯстӣ (Ҷиликул)' },
  { value: 'Jirgatol', label: 'Лахш (Ҷиргатол)' },
  { value: 'Khovaling', label: 'Ховалинг' },
  { value: 'Kuhistoni Mastchoh', label: 'Мастчоҳи Кӯҳӣ' },
  { value: 'Lakhsh', label: 'Лахш' },
  { value: 'Muminobod', label: 'Мӯъминобод' },
  { value: 'Nurobod', label: 'Нуробод' },
  { value: 'Nosiri Khusrav', label: 'Носир Хусрав' },
  { value: 'Panj', label: 'Панҷ' },
  { value: 'Rasht', label: 'Рашт' },
  { value: 'Roshtqala', label: 'Роштқалъа' },
  { value: 'Rumi', label: 'Румӣ' }, // Transliterated
  { value: 'Rudaki', label: 'Рӯдакӣ' },
  { value: 'Rushon', label: 'Рӯшон' },
  { value: 'Sangvor', label: 'Сангвор (Тавилдара)' },
  { value: 'Shughnon', label: 'Шуғнон' },
  { value: 'Temurmalik', label: 'Темурмалик' },
  { value: 'Tojikobod', label: 'Тоҷикобод' },
  { value: 'Varzob', label: 'Варзоб' },
  { value: 'Vakhsh', label: 'Вахш' },
  { value: 'Vanj', label: 'Ванҷ' },
  { value: 'Zafar', label: 'Зафар' },
  { value: 'Zarafshon', label: 'Зарафшон' }, // Transliterated
  { value: 'Yovon', label: 'Ёвон' },
  { value: 'Dusti', label: 'Дӯстӣ' },
  { value: 'Khuroson', label: 'Хуросон' },
  { value: 'Kushoniyon', label: 'Кӯшониён' },
  { value: 'Levakant', label: 'Левакант' },
  { value: 'Qubodiyon', label: 'Қубодиён' }, // Transliterated
  { value: 'Balkhi', label: 'Балхӣ' }, // Transliterated
  { value: 'Khujand', label: 'Хуҷанд' },
  { value: 'Buston', label: 'Бустон' },
  { value: 'Ghafurov', label: 'Ғафуров' }, // Transliterated
  { value: 'Isfara', label: 'Исфара' },
  { value: 'Istaravshan', label: 'Истаравшан' },
  { value: 'Konibodom', label: 'Конибодом' },
  { value: 'Mastchoh', label: 'Мастчоҳ' },
  { value: 'Spitamen', label: 'Спитамен' },
  { value: 'Zafarobod', label: 'Зафаробод' },
  { value: 'Rasulov', label: 'Расулов' },
  { value: 'Shahriston', label: 'Шаҳристон' },
  { value: 'Ayni', label: 'Айнӣ' },
  { value: 'Penjikent', label: 'Панҷакент' },
];
