import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.css';
import React from "react";
import {ThemeProvider} from "@/shared";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Zypl-head',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
