import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider, Toaster } from '@/shared';
import ReactQueryProvider from '@/shared/providers/react-query';
import { TestProvider } from '@/shared/providers/test-provider';
import './styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Zypl-head',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <ThemeProvider>
          <TestProvider>
            <body className={inter.className}>
              <Toaster />
              {children}
            </body>
          </TestProvider>
        </ThemeProvider>
      </ReactQueryProvider>
    </html>
  );
}
