import { Guide, GenderIgnore, ChoiceCourses } from '@/shared';
import { TCardMoreProps } from '@/entities';

export const moreDataCareer: TCardMoreProps[] = [
  {
    imageSrc: Guide,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Услуги по размещению и питанию',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: GenderIgnore,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Административные и вспомогательные услуги',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Сельское хозяйство, лесоводство и рыболовство',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Услуги в области искусства и отдыха',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Строительство',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Образование и профессиональная подготовка',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title:
      'Услуги по электроснабжению, газоснабжению, водоснабжению и утилизации отходов',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Финансовые и страховые услуги',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Медицинское обслуживание и социальная помощь',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Средства массовой информации и телекоммуникации',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Производство',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Добыча полезных ископаемых',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Другие услуги',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Профессиональные, научные и технические услуги',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: ChoiceCourses,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Государственное управление и безопасность',
    buttonText: 'Подробнее',
  },
];
