import {
  Botany,
  Chemistry,
  Electronics,
  MeetingWork,
  Photo,
  СompanyManagement,
  Family,
  PhysicalEducation,
  Doctor,
  Music,
  WorkingWood,
  ScienceInteres,
  PhysicsInteres,
  Institution,
  Painting,
  Rights,
  Babysitter,
  Electrician,
  Metre,
  GroupsMusic,
  Agent,
  Mechanic,
} from '@/shared';
import type { TCardDataInters } from '.';

export const CARDS_DATA_INTERES: TCardDataInters[] = [
  { src: Chemistry, title: 'Химия' },
  { src: Electronics, title: 'Электроника' },
  { src: Botany, title: 'Ботаника' },
  { src: Photo, title: 'Фотография' },
  { src: MeetingWork, title: 'Маслиҳат дар бораи кор' },
  { src: СompanyManagement, title: 'Соҳиби мағоза будан' },
  { src: Family, title: 'Роҳбарӣ кардани ширкат' },
  { src: PhysicalEducation, title: 'Ба оилаҳои эҳтиёҷман кумак расонидан' },
  { src: Doctor, title: 'Тарбияи ҷисмони' },
  { src: Music, title: 'Тиб' },
  { src: WorkingWood, title: 'Мусиқӣ' },
  { src: ScienceInteres, title: 'Кор бо чуб' },
  { src: PhysicsInteres, title: 'Илмҳои хоҷагидорӣ/иқтисодиёт' },
  { src: Institution, title: 'Физика' },
  { src: Painting, title: 'Маориф/таълим' },
  { src: Rights, title: 'Санъат' },
  { src: Babysitter, title: 'Ҳуқуқшиносӣ' },
  { src: Electrician, title: 'Санъаткор/ҳунарҳои мардумӣ' },
  { src: Metre, title: 'Нигоҳубинӣ кудак' },
  { src: GroupsMusic, title: 'Устои электроника' },
  { src: Agent, title: 'Заминченкунӣ' },
  { src: Mechanic, title: 'Дар гурӯҳ бозӣ кардан, яъзои дастаи мусиқӣ будан' },
];
