import type {
  TProfessionsClasser,
  TRelatedSociologyData,
  TSociology,
  TableDataProps,
} from '.';

export const TABLE_DATA: TableDataProps[] = [
  {
    id: 1,
    title: 'Табиӣ ва техникӣ',
  },
  {
    id: 2,
    title: 'Иқтисод ва география',
  },
  {
    id: 3,
    title: 'Филология, педагогика ва санъат',
  },
  {
    id: 4,
    title: 'Ҷомеашиносӣ ва ҳуқуқ',
  },
  {
    id: 5,
    title: 'Тиб, биология ва варзиш',
  },
];

export const professionsClasser: TProfessionsClasser[] = [
  { id: 1, title: 'Агроном', classerId: 5 },
  { id: 2, title: 'Коркарди маҳсулоти кишоварзӣ', classerId: 1 },
  { id: 3, title: 'Барқчӣ', classerId: 1 },
  { id: 4, title: 'Барқчӣ', classerId: 1 },
  { id: 5, title: 'Биология ва география', classerId: 2 },
  { id: 6, title: 'Биолог', classerId: 5 },
  { id: 7, title: 'Веб дизайнер ', classerId: 1 },
  { id: 8, title: 'Веб дизайнер ', classerId: 1 },
  { id: 9, title: 'Геодезист', classerId: 1 },
  { id: 10, title: 'Геодезист', classerId: 1 },
  { id: 11, title: 'Геолог', classerId: 1 },
  { id: 12, title: 'Геолог', classerId: 1 },
  { id: 13, title: 'Дизайнери графикӣ', classerId: 1 },
  { id: 14, title: 'Дизайнери графикӣ', classerId: 3 },
  { id: 15, title: 'Дизайнери маҳсулот', classerId: 3 },
  { id: 16, title: 'Дизайнери маҳсулот', classerId: 3 },
  { id: 17, title: 'Дорусоз', classerId: 5 },
  { id: 18, title: 'Дорусоз', classerId: 5 },
  { id: 19, title: 'Иқтисодчӣ', classerId: 2 },
  { id: 20, title: 'Иқтисодчӣ', classerId: 2 },
  { id: 21, title: 'Кимиёгар', classerId: 5 },
  { id: 22, title: 'Кимиёгар', classerId: 5 },
  { id: 23, title: 'Корманди бонк', classerId: 2 },
  { id: 24, title: 'Корманди бонк', classerId: 2 },
  { id: 25, title: 'Логистика', classerId: 1 },
  { id: 26, title: 'Логистика', classerId: 1 },
  { id: 27, title: 'Математик', classerId: 1 },
  { id: 28, title: 'Математик', classerId: 1 },
  { id: 29, title: 'Менеҷер', classerId: 2 },
  { id: 30, title: 'Менеҷер', classerId: 2 },
  { id: 31, title: 'Менеҷери амалиетӣ', classerId: 2 },
  { id: 32, title: 'Менеҷери амалиетӣ', classerId: 2 },
  {
    id: 33,
    title: 'Мутахассиси автоматикунонии фаъолияти бонкӣ',
    classerId: 1,
  },
  {
    id: 34,
    title: 'Мутахассиси автоматикунонии фаъолияти бонкӣ',
    classerId: 1,
  },
  { id: 35, title: 'Мутахассиси технологияи иттилоотӣ', classerId: 1 },
  { id: 36, title: 'Мутахассиси технологияи иттилоотӣ', classerId: 1 },
  { id: 37, title: 'Муҳандис механик', classerId: 1 },
  { id: 38, title: 'Муҳандиси автоматикунонии равандҳо', classerId: 1 },
  { id: 39, title: 'Муҳандиси барқ', classerId: 1 },
  { id: 40, title: 'Муҳандиси барқ', classerId: 1 },
  { id: 41, title: 'Муҳандиси бехатарӣ', classerId: 2 },
  { id: 42, title: 'Муҳандиси бехатарӣ', classerId: 2 },
  { id: 43, title: 'Муҳандиси бофандагӣ', classerId: 3 },
  { id: 44, title: 'Муҳандиси бофандагӣ', classerId: 3 },
  { id: 45, title: 'Муҳандиси геотехникӣ', classerId: 1 },
  { id: 46, title: 'Муҳандиси геотехникӣ', classerId: 1 },
  { id: 47, title: 'Муҳандиси кафолати сифат', classerId: 1 },
  { id: 48, title: 'Муҳандиси кафолати сифат', classerId: 1 },
  { id: 49, title: 'Муҳандиси маводшинос', classerId: 1 },
  { id: 50, title: 'Муҳандиси маводшинос', classerId: 1 },
  { id: 51, title: 'Муҳандиси сохтмон', classerId: 1 },
  { id: 52, title: 'Муҳандиси сохтмон', classerId: 1 },
  { id: 53, title: 'Муҳандиси телекоммуникатсия', classerId: 1 },
  { id: 54, title: 'Кибернетика дар иқтисодиёт', classerId: 2 },
  { id: 55, title: 'Муҳандиси телекоммуникатсия', classerId: 1 },
  { id: 56, title: 'Муҳандиси телекоммуникатсия', classerId: 1 },
  { id: 57, title: 'Муҳандиси телекоммуникатсия', classerId: 1 },
  { id: 58, title: 'Муҳандиси телекоммуникатсия', classerId: 1 },
  { id: 59, title: 'Муҳандиси экологӣ ва беҳдошт', classerId: 5 },
  { id: 60, title: 'Муҳандиси экологӣ ва муҳит', classerId: 1 },
  { id: 61, title: 'Муҳандиси энергетикӣ', classerId: 1 },
  { id: 62, title: 'Муҳандиси энергетикӣ', classerId: 1 },
  { id: 63, title: 'Оморшинос', classerId: 2 },
  { id: 64, title: 'Оморшинос', classerId: 2 },
  { id: 65, title: 'Омӯзгор', classerId: 3 },
  { id: 66, title: 'Омӯзгор', classerId: 3 },
  { id: 67, title: 'Рӯзноманигор', classerId: 3 },
  { id: 68, title: 'Рӯзноманигор', classerId: 3 },
  { id: 69, title: 'Табиб', classerId: 5 },
  { id: 70, title: 'Табиб', classerId: 5 },
  { id: 71, title: 'Таҳлилгари молиявӣ', classerId: 2 },
  { id: 72, title: 'Таҳлилгари молиявӣ', classerId: 2 },
  { id: 73, title: 'Таҳлилгари тиҷорат', classerId: 2 },
  { id: 74, title: 'Таҳлилгари тиҷорат', classerId: 2 },
  { id: 75, title: 'Физик', classerId: 1 },
  { id: 76, title: 'Физик', classerId: 1 },
  { id: 77, title: 'Химик-дорусоз', classerId: 5 },
  { id: 78, title: 'Химик-дорусоз', classerId: 5 },
  { id: 79, title: 'Ҳуқуқшинос', classerId: 4 },
  { id: 80, title: 'Ҳуқуқшинос', classerId: 4 },
  { id: 81, title: 'Иқтисодиёти энергетика', classerId: 2 },
  { id: 82, title: 'Энергетик', classerId: 1 },
];

export const uniqueProfessions = Array.from(
  new Map(professionsClasser.map((item) => [item.title, item])).values(),
);

export const tableDataWithProfessions = TABLE_DATA.map((tableEntry) => {
  const relatedProfessions = uniqueProfessions.filter(
    (profession) => profession.classerId === tableEntry.id,
  );

  return {
    ...tableEntry,
    professions: relatedProfessions,
  };
});

export const sociology: TSociology[] = [
  {
    id: 1,
    profId: 2740201,
    title: 'Агрономӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 1300,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи кишоварзии ноҳияи Мастчоҳ',
    description: '',
  },
  {
    id: 2,
    profId: 14901012501,
    title: 'Технологияи нигоҳдорӣ ва коркарди маҳсулоти кишоварзӣ-иқтисодиёт',
    type: 'фосилавӣ',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2940,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи аграрии Тоҷикистон ба номи Шириншоҳ Шоҳтемур',
    description: '',
  },
  {
    id: 3,
    profId: 153010403,
    title: 'Автоматика ва ҳифзи релеии дастгоҳҳои барқӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description: '',
  },
  {
    id: 4,
    profId: 236033101,
    title:
      'Васл ва истифодабарии таҷҳизоти барқии корхона ва биноҳои истиқоматӣ',
    type: 'рӯзона',
    class: 9,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2000,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи металлургии шаҳри Турсунзода',
    description: '',
  },
  {
    id: 5,
    profId: 102040501,
    title: 'География. Биология',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool:
      'Донишгоҳи давлатии омӯзгории Тоҷикистон ба номи Садриддин Айнӣ',
    description: '',
  },
  {
    id: 6,
    profId: 1740203,
    title: 'Ҳифзи растаниҳо ва карантин',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 3150,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Данғара',
    description: '',
  },
  {
    id: 7,
    profId: 131030408,
    title: 'WEB-дизайн ва графикаи компютерӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Кӯлоб ба номи Абӯабдуллоҳи Рӯдакӣ',
    description: '',
  },
  {
    id: 8,
    profId: 131030408,
    title: 'WEB-дизайн ва графикаи компютерӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2635,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Кӯлоб ба номи Абӯабдуллоҳи Рӯдакӣ',
    description: '',
  },
  {
    id: 9,
    profId: 1560202,
    title: 'Геодезия ва харитасозӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description: '',
  },
  {
    id: 10,
    profId: 1560101,
    title: 'Заминсозӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4500,
    lang: 'тоҷикӣ, русӣ',
    nameOfSchool: 'Донишгоҳи аграрии Тоҷикистон ба номи Шириншоҳ Шоҳтемур',
    description: '',
  },
  {
    id: 11,
    profId: 50301,
    title: 'Геология',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'русӣ',
    nameOfSchool:
      'Филиали Донишгоҳи давлатии Москва ба номи М. В. Ломоносов дар шаҳри Душанбе',
    description: '',
  },
  {
    id: 12,
    profId: 1510101,
    title: 'Геология ва ҷустуҷӯи конҳои канданиҳои фоиданок',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4907,
    lang: 'русӣ',
    nameOfSchool: 'Донишгоҳи давлатии Хоруғ ба номи Моёншо Назаршоев',
    description: '',
  },
  {
    id: 13,
    profId: 240010133,
    title: 'Графикаи компютерӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool:
      'Коллеҷи техникии Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description: '',
  },
  {
    id: 14,
    profId: 115010401,
    title: 'Графикаи дастгоҳӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишкадаи давлатии санъати тасвирӣ ва дизайни Тоҷикистон',
    description: '',
  },
  {
    id: 15,
    profId: 11901010202,
    title: 'Дизайни дохили бино',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишкадаи давлатии санъати тасвирӣ ва дизайни Тоҷикистон',
    description:
      'Беҳдошти замин ва менеҷменти хоҷагии обю Мутахассисони ин соҳа метавонандки барои хоҷагидорӣ ва истифодаи самараноки замин ва об равона карда шудааст ',
  },
  {
    id: 16,
    profId: 11901010103,
    title: 'Дизайни мебел',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4750,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишкадаи давлатии санъати тасвирӣ ва дизайни Тоҷикистон',
    description:
      'Беҳдошти замин ва менеҷменти хоҷагии обю Мутахассисони ин соҳа метавонандки барои хоҷагидорӣ ва истифодаи самараноки замин ва об равона карда шудааст ',
  },
  {
    id: 17,
    profId: 1790108,
    title: 'Дорусозӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 13300,
    lang: 'тоҷикӣ, русӣ',
    nameOfSchool: 'Донишгоҳи миллии Тоҷикистон',
    description:
      'Беҳдошти замин ва менеҷменти хоҷагии обю Мутахассисони ин соҳа метавонандки барои хоҷагидорӣ ва истифодаи самараноки замин ва об равона карда шудааст ',
  },
  {
    id: 18,
    profId: 2790108,
    title: 'Кори фарматсевтӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2600,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи тиббии ноҳияи Ёвон',
    description: '',
  },
  {
    id: 19,
    profId: 1250102,
    title: 'Иқтисодиёт',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'русӣ',
    nameOfSchool: 'Донишгоҳи (славянии) Россия ва Тоҷикистон',
    description: '',
  },
  {
    id: 20,
    profId: 1250103,
    title: 'Иқтисодиёти ҷаҳонӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4800,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Данғара',
    description: '',
  },
  {
    id: 21,
    profId: 1020403,
    title: 'Химия',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2930,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Хоруғ ба номи Моёншо Назаршоев',
    description: '',
  },
  {
    id: 22,
    profId: 1020406,
    title: 'Химияи татбиқӣ (фаъолияти илмию истеҳсолӣ)',
    type: 'фосилавӣ',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2700,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи миллии Тоҷикистон',
    description: '',
  },
  {
    id: 23,
    profId: 2250132,
    title: 'Кори бонкӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи информатика ва техникаи компютерии шаҳри Душанбе',
    description: '',
  },
  {
    id: 24,
    profId: 125010402,
    title: 'Кори бонкӣ',
    type: 'фосилавӣ',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 8300,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи миллии Тоҷикистон',
    description: '',
  },
  {
    id: 25,
    profId: 14401010105,
    title: 'Ҳамлу нақл тавассути автомашинаҳои боркаш',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ, русӣ',
    nameOfSchool: 'Донишкадаи кӯҳӣ-металлургии Тоҷикистон',
    description: '',
  },
  {
    id: 26,
    profId: 14401010105,
    title: 'Ҳамлу нақл тавассути автомашинаҳои боркаш',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4400,
    lang: 'тоҷикӣ, русӣ',
    nameOfSchool: 'Донишкадаи кӯҳӣ-металлургии Тоҷикистон',
    description: '',
  },
  {
    id: 27,
    profId: 14001,
    title: 'Воситаҳои математикӣ ва барномавӣ (ФМТДМТБ)',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'русӣ',
    nameOfSchool: 'Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description: '',
  },
  {
    id: 28,
    profId: 2020501,
    title: 'Математика',
    type: 'ғоибона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool:
      'Коллеҷи омӯзгории ба номи Хосият Махсумоваи Донишгоҳи давлатии омӯзгории Тоҷикистон ба номи Садриддин Айнӣ',
    description: '',
  },
  {
    id: 29,
    profId: 1260101,
    title: 'Идораи давлатӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4980,
    lang: 'тоҷикӣ',
    nameOfSchool:
      'Донишкадаи иқтисод ва савдои Донишгоҳи давлатии тиҷорати Тоҷикистон дар шаҳри Хуҷанд',
    description: '',
  },
  {
    id: 30,
    profId: 1260202,
    title: 'Менеҷмент',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 3850,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи байналмилалии сайёҳӣ ва соҳибкории Тоҷикистон',
    description: '',
  },
  {
    id: 31,
    profId: 227013107,
    title: 'Иқтисодиёт ва ташкили истеҳсолот дар корхонаи хоҷагии хизматрасонӣ',
    type: 'ғоибона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 1800,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи сайёҳӣ ва хидмат дар шаҳри Ваҳдат (хусусӣ)',
    description: '',
  },
  {
    id: 32,
    profId: 227013124,
    title: 'Иқтисодиёт ва ташкили истеҳсолот дар соҳаи туризм',
    type: 'рӯзона',
    class: 9,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2400,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи сайёҳӣ ва хидмат дар шаҳри Ваҳдат (хусусӣ)',
    description: '',
  },
  {
    id: 33,
    profId: 225013201,
    title: 'Автоматикунонии кори бонк',
    type: 'ғоибона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2000,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи технологии шаҳри Душанбе',
    description: '',
  },
  {
    id: 34,
    profId: 225013201,
    title: 'Автоматикунонии кори бонк',
    type: 'рӯзона',
    class: 9,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2600,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи технологии шаҳри Душанбе',
    description: '',
  },
  {
    id: 35,
    profId: 1530102,
    title: 'Автоматонии системаҳои коркарди иттилоот',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ, русӣ',
    nameOfSchool: 'Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description: '',
  },
  {
    id: 36,
    profId: 2020505,
    title: 'Информатика',
    type: 'рӯзона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 1200,
    lang: 'тоҷикӣ',
    nameOfSchool:
      'Коллеҷи омӯзгории Донишгоҳи давлатии Бохтар ба номи Носири Хусрав',
    description: '',
  },
  {
    id: 37,
    profId: 137020201,
    title: 'Вагонҳо',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description: '',
  },
  {
    id: 38,
    profId: 153010105,
    title: 'Автоматонии равандҳои технологӣ ва истеҳсолот (саноати сабук)',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4800,
    lang: 'тоҷикӣ',
    nameOfSchool:
      'Донишкадаи илмҳои дақиқ ва технологияи Тоҷикистон дар шаҳри Хуҷанд (ғайридавлатӣ)',
    description: '',
  },
  {
    id: 39,
    profId: 243010301,
    title: 'Таъминоти барқ дар корхонаҳои саноатӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2850,
    lang: 'тоҷикӣ',
    nameOfSchool:
      'Коллеҷи техникии Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description: '',
  },
  {
    id: 40,
    profId: 37665,
    title: 'Электроэнергетика ва электротехника',
    type: 'фосилавӣ',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 6322,
    lang: 'русӣ',
    nameOfSchool:
      'Филиали "Донишгоҳи миллии тадқиқотӣ" и Донишкадаи энергетикии Москва дар шаҳри Душанбе',
    description: '',
  },
  {
    id: 41,
    profId: 196010103,
    title: 'Бехатарии иқтисодӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи миллии Тоҷикистон',
    description: '',
  },
  {
    id: 42,
    profId: 196010103,
    title: 'Бехатарии иқтисодӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 7500,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи миллии Тоҷикистон',
    description: '',
  },
  {
    id: 43,
    profId: 115020102,
    title: 'Бофандагии бадеӣ. Моделиронии костюм',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 3680,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишкадаи давлатии санъати тасвирӣ ва дизайни Тоҷикистон',
    description: '',
  },
  {
    id: 44,
    profId: 119010105,
    title: 'Дизайн (костюм ва газвор)',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Данғара',
    description: '',
  },
  {
    id: 45,
    profId: 151010110,
    title: 'Гидрология ва пиряхшиносӣ',
    type: 'фосилавӣ',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2700,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи миллии Тоҷикистон',
    description: '',
  },
  {
    id: 46,
    profId: 1510201,
    title: 'Коркарди конҳои канданиҳои фоиданок (корҳои маркшейдерӣ)',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ, русӣ',
    nameOfSchool: 'Донишкадаи кӯҳӣ-металлургии Тоҷикистон',
    description: '',
  },
  {
    id: 47,
    profId: 154010104,
    title: 'Метрология, стандарткунонӣ ва сертификатсия (саноати сабук)',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 3300,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Данғара',
    description: '',
  },
  {
    id: 48,
    profId: 1540102,
    title: 'Усулҳо ва дастгоҳҳои назорати сифат ва ташхиси ҳолати иншоот',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4991,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description: '',
  },
  {
    id: 49,
    profId: 14201010101,
    title: 'Истеҳсоли рехтагарии металҳои сиёҳ ва ранга',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description:
      'Агрономӣ . Мутахассисони ин соҳа ба аҳоли кумак мерасонанд , ки чӣ тавр  заминҳоро истифода бурда ва дар кадом мавсимҳо зироат ё захир кунанд  равона карда шудааст.',
  },
  {
    id: 50,
    profId: 220300,
    title: 'Металлургия',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 10956,
    lang: 'русӣ',
    nameOfSchool:
      'Филиали Донишгоҳи миллии таҳқиқотии технологӣ "МИСиС" дар шаҳри Душанбе',
    description:
      'Агрономӣ . Мутахассисони ин соҳа ба аҳоли кумак мерасонанд , ки чӣ тавр  заминҳоро истифода бурда ва дар кадом мавсимҳо зироат ё захир кунанд  равона карда шудааст.',
  },
  {
    id: 51,
    profId: 270020105,
    title: 'Банақшагирии биноҳо ва иншоотҳо',
    type: 'рӯзона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2850,
    lang: 'тоҷикӣ',
    nameOfSchool:
      'Коллеҷи техникии Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description:
      'Агрономӣ . Мутахассисони ин соҳа ба аҳоли кумак мерасонанд , ки чӣ тавр  заминҳоро истифода бурда ва дар кадом мавсимҳо зироат ё захир кунанд  равона карда шудааст.',
  },
  {
    id: 52,
    profId: 169010107,
    title: 'Зебосозии шаҳр',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Данғара',
    description: '',
  },
  {
    id: 53,
    profId: 19801010105,
    title: 'Амнияти автоматонии системаи коркарди иттилоот ва идоракунӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description: '',
  },
  {
    id: 54,
    profId: 131030601,
    title: 'Кибернетикаи иқтисодӣ (усулҳои математикӣ дар иқтисодиёт)',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи миллии Тоҷикистон',
    description: '',
  },
  {
    id: 55,
    profId: 1390101,
    title: 'Радиотехника',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'русӣ',
    nameOfSchool: 'Донишгоҳи техникии Тоҷикистон ба номи академик М. С. Осимӣ',
    description: '',
  },
  {
    id: 56,
    profId: 140010101,
    title: 'Системаи компютерӣ ва интернет-технология',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Данғара',
    description: '',
  },
  {
    id: 57,
    profId: 2450103,
    title: 'Технологияҳои телекоммуникатсионӣ',
    type: 'ғоибона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи политехникии Донишгоҳи давлатии Данғара',
    description: '',
  },
  {
    id: 58,
    profId: 1450103,
    title: 'Шабакаҳои телекоммуникатсионӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ, русӣ',
    nameOfSchool: 'Донишгоҳи технологии Тоҷикистон',
    description: '',
  },
  {
    id: 59,
    profId: 1330106,
    title: 'Агроэкология',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Хуҷанд ба номи академик Бобоҷон Ғафуров',
    description: '',
  },
  {
    id: 60,
    profId: 17405012602,
    title: 'Беҳдошти замин ва менеҷменти хоҷагии об',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи аграрии Тоҷикистон ба номи Шириншоҳ Шоҳтемур',
    description: '',
  },
  {
    id: 61,
    profId: 1430104,
    title: 'Истгоҳҳои барқии ҳароратӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4490,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишкадаи энергетикии Тоҷикистон',
    description: '',
  },
  {
    id: 62,
    profId: 243010131,
    title: 'Истифодабарии таҷҳизоти нерӯгоҳҳо ва нерӯгоҳҳои хурди барқӣ',
    type: 'рӯзона',
    class: 9,
    education: 'Миёнаи касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи муҳандисӣ‐омӯзгории шаҳри Душанбе',
    description:
      'Зоотехния . Мутахассисони ин соҳа метавонанд , ки дар боғи ҳайвонот ҳамчун техник кор кардан рвона карда шудааст.',
  },
  {
    id: 63,
    profId: 2250105,
    title: 'Омор',
    type: 'рӯзона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 1468,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи омори шаҳри Ваҳдат',
    description: '',
  },
  {
    id: 64,
    profId: 1250105,
    title: 'Омор',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии молия ва иқтисоди Тоҷикистон',
    description:
      'Марғзорпарварӣ (чарогоҳпарварӣ). Мутахассисониин соҳа барои эмин доштани ҳайвонҳои  нодир аз ҳар гуна ҳодисаҳои гирду атроф ва парвариш кардани марғзорҳо равона карда шудааст.',
  },
  {
    id: 65,
    profId: 2020302,
    title: 'Забон ва адабиёти рус',
    type: 'рӯзона',
    class: 9,
    education: 'Миёнаи касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'русӣ',
    nameOfSchool:
      'Коллеҷи омӯзгории Донишгоҳи давлатии Хуҷанд ба номи академик Бобоҷон Ғафуров',
    description:
      'Зоотехния . Мутахассисони ин соҳа метавонанд , ки дар боғи ҳайвонот ҳамчун техник кор кардан рвона карда шудааст.',
  },
  {
    id: 66,
    profId: 2020301,
    title: 'Забон ва адабиёти тоҷик',
    type: 'ғоибона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool:
      'Коллеҷи омӯзгории ба номи Хосият Махсумоваи Донишгоҳи давлатии омӯзгории Тоҷикистон ба номи Садриддин Айнӣ',
    description:
      'Зоотехния . Мутахассисони ин соҳа метавонанд , ки дар боғи ҳайвонот ҳамчун техник кор кардан рвона карда шудааст.',
  },
  {
    id: 67,
    profId: 123010801,
    title: 'Рӯзноманигорӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 5040,
    lang: 'русӣ',
    nameOfSchool: 'Донишгоҳи (славянии) Россия ва Тоҷикистон',
    description: '',
  },
  {
    id: 68,
    profId: 12301080201,
    title: 'Рӯзноманигори телевизион',
    type: 'фосилавӣ',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 3410,
    lang: 'тоҷикӣ',
    nameOfSchool:
      'Донишкадаи давлатии фарҳанг ва санъати Тоҷикистон ба номи Мирзо Турсунзода',
    description: '',
  },
  {
    id: 69,
    profId: 2790102,
    title: 'Кори момодоягӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2500,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи тиббии шаҳри Турсунзода',
    description: '',
  },
  {
    id: 70,
    profId: 1790101,
    title: 'Кори табобатӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии тиббии Хатлон',
    description: '',
  },
  {
    id: 71,
    profId: 125010809,
    title: 'Баҳисобгирии бухгалтерӣ, таҳлил ва аудит дар комплекси агросаноатӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 5000,
    lang: 'тоҷикӣ, русӣ',
    nameOfSchool: 'Донишгоҳи аграрии Тоҷикистон ба номи Шириншоҳ Шоҳтемур',
    description: '',
  },
  {
    id: 72,
    profId: 125010803,
    title:
      'Баҳисобгирии бухгалтерӣ, таҳлил ва аудит дар муассисаҳои буҷетӣ ва илмӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4650,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Кӯлоб ба номи Абӯабдуллоҳи Рӯдакӣ',
    description: '',
  },
  {
    id: 73,
    profId: 227013123,
    title: 'Иқтисодиёт ва ташкил дар соҳаи сайёҳӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2380,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи муҳандисӣ‐омӯзгории шаҳри Душанбе',
    description:
      'Марғзорпарварӣ (чарогоҳпарварӣ). Мутахассисониин соҳа барои эмин доштани ҳайвонҳои  нодир аз ҳар гуна ҳодисаҳои гирду атроф ва парвариш кардани марғзорҳо равона карда шудааст.',
  },
  {
    id: 74,
    profId: 227013126,
    title: 'Иқтисодиёт ва ташкили хоҷагии тарабхонаҳо',
    type: 'рӯзона',
    class: 9,
    education: 'Миёнаи касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2400,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Коллеҷи сайёҳӣ ва хидмат дар шаҳри Ваҳдат (хусусӣ)',
    description: '',
  },
  {
    id: 75,
    profId: 1020502,
    title: 'Физика',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 2930,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Хоруғ ба номи Моёншо Назаршоев',
    description: '',
  },
  {
    id: 76,
    profId: 102050405,
    title: 'Физика. Информатика. Астрономия',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии Бохтар ба номи Носири Хусрав',
    description: '',
  },
  {
    id: 77,
    profId: 1740302790108,
    title: 'Тибби байторӣ-фарматсевт',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 3500,
    lang: 'тоҷикӣ, русӣ',
    nameOfSchool: 'Донишгоҳи аграрии Тоҷикистон ба номи Шириншоҳ Шоҳтемур',
    description: '',
  },
  {
    id: 78,
    profId: 131050103,
    title: 'Химия (фаъолияти дорусозӣ)',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'русӣ',
    nameOfSchool:
      'Донишкадаи технология ва менеҷменти инноватсионӣ дар шаҳри Кӯлоб',
    description: '',
  },
  {
    id: 79,
    profId: 1260102,
    title: 'Идораи давлатӣ ва ҳуқуқ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи миллии Тоҷикистон',
    description: '',
  },
  {
    id: 80,
    profId: 196010101,
    title: 'Таъмини ҳуқуқии фаъолияти гумрукӣ',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'ройгон',
    educationPrice: 0,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи давлатии молия ва иқтисоди Тоҷикистон',
    description: '',
  },
  {
    id: 81,
    profId: 127010110,
    title: 'Иқтисодиёт ва ташкили истеҳсолот (энергетика)',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4025,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишгоҳи байналмилалии сайёҳӣ ва соҳибкории Тоҷикистон',
    description: '',
  },
  {
    id: 82,
    profId: 143010505,
    title: 'Манбаъҳои барқароршавандаи ғайрианъанавии энергия',
    type: 'рӯзона',
    class: 11,
    education: 'Олии касбӣ',
    educationType: 'пулакӣ',
    educationPrice: 4490,
    lang: 'тоҷикӣ',
    nameOfSchool: 'Донишкадаи энергетикии Тоҷикистон',
    description: '',
  },
];

export const relatedSociologyData: TRelatedSociologyData[] =
  uniqueProfessions.map((profession) => {
    return {
      ...profession,
      sociology: professionsClasser
        .filter((prof) => prof.title === profession.title)
        .map((p) => sociology[p.id - 1]),
    };
  });
