name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - ci_cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY_BASE64 }}" | base64 --decode > private_key.pem
          chmod 600 private_key.pem

      - name: Debug SSH Connection
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} "echo SSH Connection Successful"

      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd /home/zypl_career/script/deploy.sh
