name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to Google Cloud instance
      - name: Deploy to Google Cloud
        run: |
          ssh -o StrictHostKeyChecking=no user@${{ secrets.GC_INSTANCE_IP }} /home/zypl_career/deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GC_INSTANCE_PRIVATE_KEY }}
