import {
  Ilmhona,
  Repititor,
  Lider,
  Edgir,
  Qalam,
  CentralAsia,
  AmericanSchool,
  CenterIct,
  AlifAcademy,
} from '@/shared';
import type { TCardMoreProps } from '@/entities';

export const TRAINING_CARD_DATA: TCardMoreProps[] = [
  {
    imageSrc: Ilmhona,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Акселератор навыков «Илмхона»',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Repititor,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Образовательный центр «Repetitor.tj»',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Lider,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Учебный центр «Лидер»',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Edgir,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Учебный центр «Ёдгир»',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: Qalam,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Образовательный центр «Qalam»',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: CentralAsia,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Университет Центральной Азии',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: AmericanSchool,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'American School',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: CenterIct,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'Центр  «Информационно-Коммуникационных Технологий» (Центр ИКТ)',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
  {
    imageSrc: AlifAcademy,
    imageAlt: 'guide',
    imageHeight: 300,
    imageWidth: 470,
    title: 'AlifAcademy',
    date: '1 сентября',
    buttonText: 'Подробнее',
  },
];
